### ISSUE TITLE
Inactive alarms in Panic are activated automatically if we restart PyAlarm DS.

### ISSUE THREAD

**Issue by mrosanes** [tango-controls/PANIC#36] opened 2019-09-03 14:08 UTC
Some inactive alarms in Panic are activated automatically if we restart PyAlarm DS (03/09/2019).

Status persistence of active / inactive alarms is not kept if PyAlarm DS is restarted: from panic we can see that some of the alarms that were inactive, are active again if we restart the PyAlarm DS.

**Comment by sergirubio** [comment] 2019-09-03 14:10
Hi, if you refer to disabled alarms, this is the expected behavior.

Persistence is avoided by design (as it's more dangerous to have an 
alarm disabled)

Sergi

**Comment by sergirubio** [comment] 2019-09-03 14:11
for reloading configuration of PyAlarm device it's enough to execute 
Init() command; a full server restart is not needed.

**Comment by mrosanes** [comment] 2019-09-03 14:20
I wanted to try to restart in order to see if this could solve issue #32 with the color status of Alarms in the GUI; but it does not seem the case.

In the other hand, in my opinion, it would be more logic to keep the persistence of the same alarm status existing before restarting the PyAlarmDS, rather than activate by default all alarms after a PyAlarmDS restart. I am thinking e.g. in a case of a laboratory that in nominal conditions could use a high number of active and inactive alarms (e.g: about 50 active alarms and 20 inactive alarms); after restarting the PyAlarmDS it could be difficult to remember all alarms that the scientists should disable again to come back to the previous state, existing before the restart of the PyAlarmDS.

**Comment by mrosanes** [comment] 2019-09-03 14:23
you can check these alarms in panic from pcbl0905:
- mistral_bakeout_low_temp is correctly deactivated (grey color)
- mistral_bakeout_M4_comms is correctly deactivated (grey color)
- mistral_bakeout_high_temp is incorrectly deactivated (the alarm is inactive but it remains in green in panicGUI)
- mistral_bakeout_pressure_m4 is incorrectly deactivated (the alarm is inactive but it remains in green in panicGUI)

**Comment by sergirubio** [comment] 2022-03-24 14:53
hi, the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you

**Closed as completed by sergirubio** 2022-03-24 14:53 UTC
